I exchanged http://json-schema.org/draft-07/schema by http://json-schema.org/draft-07/schema in all files.
dbe.json and dsb.json are valid:
D:\Users\cmaurer\Desktop\200418_HomeOffice\SCOPE\dbe-data-schema-for-building-envelopes\schemas>ajv compile -s dbe.json -r calorimetric.json -r common.json -r component.json -r gaps.json -r geometry.json -r hygrothermal.json -r identifier.json -r layer.json -r material.json -r method.json -r number.json -r optical.json -r photovoltaic.json -r stakeholder.json -r string.json -r unit.json
schema dbe.json is valid
D:\Users\cmaurer\Desktop\200418_HomeOffice\SCOPE\dbe-data-schema-for-building-envelopes\schemas>ajv compile -s dsb.json -r dbe.json -r calorimetric.json -r common.json -r component.json -r gaps.json -r geometry.json -r hygrothermal.json -r identifier.json -r layer.json -r material.json -r method.json -r number.json -r optical.json -r photovoltaic.json -r stakeholder.json -r string.json -r unit.json -r building.json
schema dsb.json is valid

They are not valid if "title" is a number instead of a string:
D:\Users\cmaurer\Desktop\200418_HomeOffice\SCOPE\dbe-data-schema-for-building-envelopes\schemas>ajv compile -s dsb.json -r dbe.json -r calorimetric.json -r common.json -r component.json -r gaps.json -r geometry.json -r hygrothermal.json -r identifier.json -r layer.json -r material.json -r method.json -r number.json -r optical.json -r photovoltaic.json -r stakeholder.json -r string.json -r unit.json -r building.json
schema dbe.json is invalid
error: schema is invalid: data.title should be string